package stock_parser

// Code generated by peg -inline -switch -output grammar.go grammar.peg DO NOT EDIT.

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	ruleItem
	ruleLine
	ruleOTHER
	ruleStock
	ruleXLStock
	ruleFTStock
	ruleStockName
	ruleCode
	ruleUSCode
	ruleHKCode
	ruleACode
	ruleLetter
	ruleNumber
	ruleSuffix
	ruleMarket
	ruleCNMarket
	ruleHKMarket
	ruleUSMarket
	ruleSGMarket
	ruleSP
)

var rul3s = [...]string{
	"Unknown",
	"Item",
	"Line",
	"OTHER",
	"Stock",
	"XLStock",
	"FTStock",
	"StockName",
	"Code",
	"USCode",
	"HKCode",
	"ACode",
	"Letter",
	"Number",
	"Suffix",
	"Market",
	"CNMarket",
	"HKMarket",
	"USMarket",
	"SGMarket",
	"SP",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type node32 struct {
	token32
	up, next *node32
}

func (node *node32) print(w io.Writer, pretty bool, buffer string) {
	var print func(node *node32, depth int)
	print = func(node *node32, depth int) {
		for node != nil {
			for c := 0; c < depth; c++ {
				fmt.Fprintf(w, " ")
			}
			rule := rul3s[node.pegRule]
			quote := strconv.Quote(string(([]rune(buffer)[node.begin:node.end])))
			if !pretty {
				fmt.Fprintf(w, "%v %v\n", rule, quote)
			} else {
				fmt.Fprintf(w, "\x1B[36m%v\x1B[m %v\n", rule, quote)
			}
			if node.up != nil {
				print(node.up, depth+1)
			}
			node = node.next
		}
	}
	print(node, 0)
}

func (node *node32) Print(w io.Writer, buffer string) {
	node.print(w, false, buffer)
}

func (node *node32) PrettyPrint(w io.Writer, buffer string) {
	node.print(w, true, buffer)
}

type tokens32 struct {
	tree []token32
}

func (t *tokens32) Trim(length uint32) {
	t.tree = t.tree[:length]
}

func (t *tokens32) Print() {
	for _, token := range t.tree {
		fmt.Println(token.String())
	}
}

func (t *tokens32) AST() *node32 {
	type element struct {
		node *node32
		down *element
	}
	tokens := t.Tokens()
	var stack *element
	for _, token := range tokens {
		if token.begin == token.end {
			continue
		}
		node := &node32{token32: token}
		for stack != nil && stack.node.begin >= token.begin && stack.node.end <= token.end {
			stack.node.next = node.up
			node.up = stack.node
			stack = stack.down
		}
		stack = &element{node: node, down: stack}
	}
	if stack != nil {
		return stack.node
	}
	return nil
}

func (t *tokens32) PrintSyntaxTree(buffer string) {
	t.AST().Print(os.Stdout, buffer)
}

func (t *tokens32) WriteSyntaxTree(w io.Writer, buffer string) {
	t.AST().Print(w, buffer)
}

func (t *tokens32) PrettyPrintSyntaxTree(buffer string) {
	t.AST().PrettyPrint(os.Stdout, buffer)
}

func (t *tokens32) Add(rule pegRule, begin, end, index uint32) {
	tree, i := t.tree, int(index)
	if i >= len(tree) {
		t.tree = append(tree, token32{pegRule: rule, begin: begin, end: end})
		return
	}
	tree[i] = token32{pegRule: rule, begin: begin, end: end}
}

func (t *tokens32) Tokens() []token32 {
	return t.tree
}

type StockCodeParser struct {
	pos     int
	peekPos int

	Buffer string
	buffer []rune
	rules  [21]func() bool
	parse  func(rule ...int) error
	reset  func()
	Pretty bool
	tokens32
}

func (p *StockCodeParser) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *StockCodeParser) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *StockCodeParser
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func (p *StockCodeParser) PrintSyntaxTree() {
	if p.Pretty {
		p.tokens32.PrettyPrintSyntaxTree(p.Buffer)
	} else {
		p.tokens32.PrintSyntaxTree(p.Buffer)
	}
}

func (p *StockCodeParser) WriteSyntaxTree(w io.Writer) {
	p.tokens32.WriteSyntaxTree(w, p.Buffer)
}

func (p *StockCodeParser) SprintSyntaxTree() string {
	var bldr strings.Builder
	p.WriteSyntaxTree(&bldr)
	return bldr.String()
}

func Pretty(pretty bool) func(*StockCodeParser) error {
	return func(p *StockCodeParser) error {
		p.Pretty = pretty
		return nil
	}
}

func Size(size int) func(*StockCodeParser) error {
	return func(p *StockCodeParser) error {
		p.tokens32 = tokens32{tree: make([]token32, 0, size)}
		return nil
	}
}
func (p *StockCodeParser) Init(options ...func(*StockCodeParser) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0

		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	tree := p.tokens32
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		p.tokens32 = tree
		if matches {
			p.Trim(tokenIndex)
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tree.Add(rule, begin, position, tokenIndex)
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	matchDot := func() bool {
		if buffer[position] != endSymbol {
			position++
			return true
		}
		return false
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	/*matchRange := func(lower byte, upper byte) bool {
		if c := buffer[position]; c >= lower && c <= upper {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 Item <- <(Line* !.)> */
		func() bool {
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
			l2:
				{
					position3, tokenIndex3 := position, tokenIndex
					{
						position4 := position
						{
							position5, tokenIndex5 := position, tokenIndex
							{
								position7 := position
								if buffer[position] != rune('$') {
									goto l6
								}
								position++
								if !_rules[ruleStockName]() {
									goto l6
								}
								if buffer[position] != rune('(') {
									goto l6
								}
								position++
								if !_rules[ruleCode]() {
									goto l6
								}
								if buffer[position] != rune('.') {
									goto l6
								}
								position++
								if !_rules[ruleMarket]() {
									goto l6
								}
								if buffer[position] != rune(')') {
									goto l6
								}
								position++
								if buffer[position] != rune('$') {
									goto l6
								}
								position++
								add(ruleFTStock, position7)
							}
							goto l5
						l6:
							position, tokenIndex = position5, tokenIndex5
							{
								position9 := position
								if buffer[position] != rune('$') {
									goto l8
								}
								position++
								if !_rules[ruleStockName]() {
									goto l8
								}
								if buffer[position] != rune('(') {
									goto l8
								}
								position++
								{
									position10, tokenIndex10 := position, tokenIndex
									if !_rules[ruleCNMarket]() {
										goto l11
									}
									if !_rules[ruleACode]() {
										goto l11
									}
									goto l10
								l11:
									position, tokenIndex = position10, tokenIndex10
									if !_rules[ruleUSCode]() {
										goto l12
									}
									goto l10
								l12:
									position, tokenIndex = position10, tokenIndex10
									if !_rules[ruleHKCode]() {
										goto l8
									}
								}
							l10:
								if buffer[position] != rune(')') {
									goto l8
								}
								position++
								if buffer[position] != rune('$') {
									goto l8
								}
								position++
								add(ruleXLStock, position9)
							}
							goto l5
						l8:
							position, tokenIndex = position5, tokenIndex5
							{
								position14 := position
								{
									position15, tokenIndex15 := position, tokenIndex
									if buffer[position] != rune('$') {
										goto l16
									}
									position++
									if !_rules[ruleCode]() {
										goto l16
									}
									{
										position17, tokenIndex17 := position, tokenIndex
										if !_rules[ruleSuffix]() {
											goto l18
										}
										goto l17
									l18:
										position, tokenIndex = position17, tokenIndex17
										{
											position19, tokenIndex19 := position, tokenIndex
											if !_rules[ruleSuffix]() {
												goto l19
											}
											goto l20
										l19:
											position, tokenIndex = position19, tokenIndex19
										}
									l20:
									}
								l17:
									if buffer[position] != rune('$') {
										goto l16
									}
									position++
									goto l15
								l16:
									position, tokenIndex = position15, tokenIndex15
									{
										position22, tokenIndex22 := position, tokenIndex
										if buffer[position] != rune('$') {
											goto l22
										}
										position++
										goto l23
									l22:
										position, tokenIndex = position22, tokenIndex22
									}
								l23:
									if !_rules[ruleCode]() {
										goto l21
									}
									if !_rules[ruleSuffix]() {
										goto l21
									}
									goto l15
								l21:
									position, tokenIndex = position15, tokenIndex15
									if buffer[position] != rune('$') {
										goto l24
									}
									position++
									if !_rules[ruleUSCode]() {
										goto l24
									}
									goto l15
								l24:
									position, tokenIndex = position15, tokenIndex15
									if buffer[position] != rune('(') {
										goto l13
									}
									position++
									{
										position25, tokenIndex25 := position, tokenIndex
										if buffer[position] != rune('N') {
											goto l26
										}
										position++
										if buffer[position] != rune('Y') {
											goto l26
										}
										position++
										if buffer[position] != rune('S') {
											goto l26
										}
										position++
										if buffer[position] != rune('E') {
											goto l26
										}
										position++
										goto l25
									l26:
										position, tokenIndex = position25, tokenIndex25
										if buffer[position] != rune('N') {
											goto l13
										}
										position++
										if buffer[position] != rune('A') {
											goto l13
										}
										position++
										if buffer[position] != rune('S') {
											goto l13
										}
										position++
										if buffer[position] != rune('D') {
											goto l13
										}
										position++
										if buffer[position] != rune('A') {
											goto l13
										}
										position++
										if buffer[position] != rune('Q') {
											goto l13
										}
										position++
									}
								l25:
									{
										position27, tokenIndex27 := position, tokenIndex
										if buffer[position] != rune('：') {
											goto l28
										}
										position++
										goto l27
									l28:
										position, tokenIndex = position27, tokenIndex27
										if buffer[position] != rune(':') {
											goto l13
										}
										position++
									}
								l27:
								l29:
									{
										position30, tokenIndex30 := position, tokenIndex
										{
											position31 := position
											{
												position32, tokenIndex32 := position, tokenIndex
												if buffer[position] != rune(' ') {
													goto l33
												}
												position++
												goto l32
											l33:
												position, tokenIndex = position32, tokenIndex32
												if buffer[position] != rune('\t') {
													goto l30
												}
												position++
											}
										l32:
											add(ruleSP, position31)
										}
										goto l29
									l30:
										position, tokenIndex = position30, tokenIndex30
									}
									if !_rules[ruleUSCode]() {
										goto l13
									}
									if buffer[position] != rune(')') {
										goto l13
									}
									position++
								}
							l15:
								add(ruleStock, position14)
							}
							goto l5
						l13:
							position, tokenIndex = position5, tokenIndex5
							{
								position34 := position
								if !matchDot() {
									goto l3
								}
								add(ruleOTHER, position34)
							}
						}
					l5:
						add(ruleLine, position4)
					}
					goto l2
				l3:
					position, tokenIndex = position3, tokenIndex3
				}
				{
					position35, tokenIndex35 := position, tokenIndex
					if !matchDot() {
						goto l35
					}
					goto l0
				l35:
					position, tokenIndex = position35, tokenIndex35
				}
				add(ruleItem, position1)
			}
			return true
		l0:
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 Line <- <(FTStock / XLStock / Stock / OTHER)> */
		nil,
		/* 2 OTHER <- <.> */
		nil,
		/* 3 Stock <- <(('$' Code (Suffix / Suffix?) '$') / ('$'? Code Suffix) / ('$' USCode) / ('(' (('N' 'Y' 'S' 'E') / ('N' 'A' 'S' 'D' 'A' 'Q')) ('：' / ':') SP* USCode ')'))> */
		nil,
		/* 4 XLStock <- <('$' StockName '(' ((CNMarket ACode) / USCode / HKCode) ')' '$')> */
		nil,
		/* 5 FTStock <- <('$' StockName '(' Code '.' Market ')' '$')> */
		nil,
		/* 6 StockName <- <(!('(' / ')') .)+> */
		func() bool {
			position41, tokenIndex41 := position, tokenIndex
			{
				position42 := position
				{
					position45, tokenIndex45 := position, tokenIndex
					{
						position46, tokenIndex46 := position, tokenIndex
						if buffer[position] != rune('(') {
							goto l47
						}
						position++
						goto l46
					l47:
						position, tokenIndex = position46, tokenIndex46
						if buffer[position] != rune(')') {
							goto l45
						}
						position++
					}
				l46:
					goto l41
				l45:
					position, tokenIndex = position45, tokenIndex45
				}
				if !matchDot() {
					goto l41
				}
			l43:
				{
					position44, tokenIndex44 := position, tokenIndex
					{
						position48, tokenIndex48 := position, tokenIndex
						{
							position49, tokenIndex49 := position, tokenIndex
							if buffer[position] != rune('(') {
								goto l50
							}
							position++
							goto l49
						l50:
							position, tokenIndex = position49, tokenIndex49
							if buffer[position] != rune(')') {
								goto l48
							}
							position++
						}
					l49:
						goto l44
					l48:
						position, tokenIndex = position48, tokenIndex48
					}
					if !matchDot() {
						goto l44
					}
					goto l43
				l44:
					position, tokenIndex = position44, tokenIndex44
				}
				add(ruleStockName, position42)
			}
			return true
		l41:
			position, tokenIndex = position41, tokenIndex41
			return false
		},
		/* 7 Code <- <(USCode / HKCode / ACode)> */
		func() bool {
			position51, tokenIndex51 := position, tokenIndex
			{
				position52 := position
				{
					position53, tokenIndex53 := position, tokenIndex
					if !_rules[ruleUSCode]() {
						goto l54
					}
					goto l53
				l54:
					position, tokenIndex = position53, tokenIndex53
					if !_rules[ruleHKCode]() {
						goto l55
					}
					goto l53
				l55:
					position, tokenIndex = position53, tokenIndex53
					if !_rules[ruleACode]() {
						goto l51
					}
				}
			l53:
				add(ruleCode, position52)
			}
			return true
		l51:
			position, tokenIndex = position51, tokenIndex51
			return false
		},
		/* 8 USCode <- <Letter+> */
		func() bool {
			position56, tokenIndex56 := position, tokenIndex
			{
				position57 := position
				{
					position60 := position
					if c := buffer[position]; c < rune('A') || c > rune('Z') {
						goto l56
					}
					position++
					add(ruleLetter, position60)
				}
			l58:
				{
					position59, tokenIndex59 := position, tokenIndex
					{
						position61 := position
						if c := buffer[position]; c < rune('A') || c > rune('Z') {
							goto l59
						}
						position++
						add(ruleLetter, position61)
					}
					goto l58
				l59:
					position, tokenIndex = position59, tokenIndex59
				}
				add(ruleUSCode, position57)
			}
			return true
		l56:
			position, tokenIndex = position56, tokenIndex56
			return false
		},
		/* 9 HKCode <- <Number+> */
		func() bool {
			position62, tokenIndex62 := position, tokenIndex
			{
				position63 := position
				if !_rules[ruleNumber]() {
					goto l62
				}
			l64:
				{
					position65, tokenIndex65 := position, tokenIndex
					if !_rules[ruleNumber]() {
						goto l65
					}
					goto l64
				l65:
					position, tokenIndex = position65, tokenIndex65
				}
				add(ruleHKCode, position63)
			}
			return true
		l62:
			position, tokenIndex = position62, tokenIndex62
			return false
		},
		/* 10 ACode <- <Number+> */
		func() bool {
			position66, tokenIndex66 := position, tokenIndex
			{
				position67 := position
				if !_rules[ruleNumber]() {
					goto l66
				}
			l68:
				{
					position69, tokenIndex69 := position, tokenIndex
					if !_rules[ruleNumber]() {
						goto l69
					}
					goto l68
				l69:
					position, tokenIndex = position69, tokenIndex69
				}
				add(ruleACode, position67)
			}
			return true
		l66:
			position, tokenIndex = position66, tokenIndex66
			return false
		},
		/* 11 Letter <- <[A-Z]> */
		nil,
		/* 12 Number <- <[0-9]> */
		func() bool {
			position71, tokenIndex71 := position, tokenIndex
			{
				position72 := position
				if c := buffer[position]; c < rune('0') || c > rune('9') {
					goto l71
				}
				position++
				add(ruleNumber, position72)
			}
			return true
		l71:
			position, tokenIndex = position71, tokenIndex71
			return false
		},
		/* 13 Suffix <- <('.' (Market / ('o' / 'O')))> */
		func() bool {
			position73, tokenIndex73 := position, tokenIndex
			{
				position74 := position
				if buffer[position] != rune('.') {
					goto l73
				}
				position++
				{
					position75, tokenIndex75 := position, tokenIndex
					if !_rules[ruleMarket]() {
						goto l76
					}
					goto l75
				l76:
					position, tokenIndex = position75, tokenIndex75
					{
						position77, tokenIndex77 := position, tokenIndex
						if buffer[position] != rune('o') {
							goto l78
						}
						position++
						goto l77
					l78:
						position, tokenIndex = position77, tokenIndex77
						if buffer[position] != rune('O') {
							goto l73
						}
						position++
					}
				l77:
				}
			l75:
				add(ruleSuffix, position74)
			}
			return true
		l73:
			position, tokenIndex = position73, tokenIndex73
			return false
		},
		/* 14 Market <- <(CNMarket / ((&('S') SGMarket) | (&('U') USMarket) | (&('H') HKMarket)))> */
		func() bool {
			position79, tokenIndex79 := position, tokenIndex
			{
				position80 := position
				{
					position81, tokenIndex81 := position, tokenIndex
					if !_rules[ruleCNMarket]() {
						goto l82
					}
					goto l81
				l82:
					position, tokenIndex = position81, tokenIndex81
					{
						switch buffer[position] {
						case 'S':
							{
								position84 := position
								if buffer[position] != rune('S') {
									goto l79
								}
								position++
								if buffer[position] != rune('G') {
									goto l79
								}
								position++
								add(ruleSGMarket, position84)
							}
						case 'U':
							{
								position85 := position
								if buffer[position] != rune('U') {
									goto l79
								}
								position++
								if buffer[position] != rune('S') {
									goto l79
								}
								position++
								add(ruleUSMarket, position85)
							}
						default:
							{
								position86 := position
								if buffer[position] != rune('H') {
									goto l79
								}
								position++
								if buffer[position] != rune('K') {
									goto l79
								}
								position++
								add(ruleHKMarket, position86)
							}
						}
					}

				}
			l81:
				add(ruleMarket, position80)
			}
			return true
		l79:
			position, tokenIndex = position79, tokenIndex79
			return false
		},
		/* 15 CNMarket <- <(('S' 'H') / ('S' 'Z'))> */
		func() bool {
			position87, tokenIndex87 := position, tokenIndex
			{
				position88 := position
				{
					position89, tokenIndex89 := position, tokenIndex
					if buffer[position] != rune('S') {
						goto l90
					}
					position++
					if buffer[position] != rune('H') {
						goto l90
					}
					position++
					goto l89
				l90:
					position, tokenIndex = position89, tokenIndex89
					if buffer[position] != rune('S') {
						goto l87
					}
					position++
					if buffer[position] != rune('Z') {
						goto l87
					}
					position++
				}
			l89:
				add(ruleCNMarket, position88)
			}
			return true
		l87:
			position, tokenIndex = position87, tokenIndex87
			return false
		},
		/* 16 HKMarket <- <('H' 'K')> */
		nil,
		/* 17 USMarket <- <('U' 'S')> */
		nil,
		/* 18 SGMarket <- <('S' 'G')> */
		nil,
		/* 19 SP <- <(' ' / '\t')> */
		nil,
	}
	p.rules = _rules
	return nil
}
